---
- name: pull latest code from git
  git:
    repo: ssh://git@github.com/HanxunHuangLemonBear/COMP90024-2019S1-Team7.git
    key_file: /home/ubuntu/.ssh/GitHub
    update: yes
    dest: '{{ remote_working_directory }}'
    force: yes

- name: copy compose file to server
  become: yes
  template:
    src: web-docker-compose.yaml.j2
    dest: '/home/ubuntu/docker-compose.yaml'
    owner: ubuntu
    group: ubuntu

- name: copy nginx config to server
  become: yes
  template:
    src: web-nginx.conf.j2
    dest: '{{remote_working_directory}}/config/webserver_nginx/nginx.conf'
    owner: ubuntu
    group: ubuntu
