- hosts: localhost
  vars_files:
    - host_vars/nectar.yaml
  gather_facts: true

  roles:
    - role: openstack-common
    - role: openstack-images
    - role: openstack-volume
    - role: openstack-security-group
    - role: openstack-instance
    - role: openstack-volume-snapshot